/**
 * Domain types for the users microservice.
 *
 * These types describe the in-memory data model used in the minimal preset.
 * Phase 6 (database preset) replaces the in-memory store with DynamoDB/RDS
 * while keeping these type definitions stable.
 */

// ---------------------------------------------------------------------------
// Domain model
// ---------------------------------------------------------------------------

/**
 * A user record stored in the service.
 *
 * `id` is a UUID v4 generated by `crypto.randomUUID()` at creation time.
 * `createdAt` and `updatedAt` are ISO-8601 strings set automatically.
 */
export interface User {
  id: string;
  name: string;
  email: string;
  createdAt: string;
  updatedAt: string;
}

// ---------------------------------------------------------------------------
// Request bodies
// ---------------------------------------------------------------------------

/**
 * Fields accepted when creating a new user.
 * The `id`, `createdAt`, and `updatedAt` fields are server-generated.
 */
export interface CreateUserBody {
  name: string;
  email: string;
}

/**
 * Fields accepted when updating an existing user.
 * All fields are optional — only the provided fields are changed.
 */
export interface UpdateUserBody {
  name?: string;
  email?: string;
}
